### ISSUE TITLE
synthetic/sum_is_commutative_klee_float_bug.x86_64 is missing counter examples

### ISSUE THREAD

**Issue by delcypher** [delcypher/fp-benchmarks-imperial#4]
```
WARNING:MainThread: MATCH SPEC for task no_invalid_deref but with warnings:
/home/user/build_O2/benchmarks/c/imperial/synthetic/sum_is_commutative_klee_float_bug.x86_64.bc (/home/dsl11/dev/klee-afr/experiments/first/wd/workdir-83/klee-wd)
Observed counter examples not listed in spec
  Test 000006 in /home/user/fp-bench/benchmarks/c/imperial/synthetic/sum_is_commutative/sum_is_commutative.c:40
```

@afd This is your benchmark. Could you added the out of bound memory access to the list of counter examples for `no_invalid_deref` verification task.

**Comment by afd** [comment]
Hi Dan

There is not supposed to be an out of bounds access for this benchmark, and looking at the code I cannot see how one can occur.  Are you able to point to where the benchmark is wrong?  If you can, the solution should be to fix the program, not change its spec.

**Comment by delcypher** [comment]
@afd The `spec.yml` file lists `no_invalid_deref` as expected to be incorrect.

```
  klee_float_bug:
    categories:
      - issta_2017
    defines:
      FLOAT_TYPE: float
      KLEE: null
      N: "5"
      BUG: "1"
    dependencies:
      klee_runtime: {}
    verification_tasks:
      no_assert_fail:
        correct: false
        counter_examples:
          -
            description: >
              An injected bug messes up one of the loop conditions,
              which will stop the sums from matching
            locations:
              -
                file: "sum_is_commutative.c" 
                line: 72

      no_invalid_deref:
        correct: false
        description: >
          The messed up bounds may cause and out-of-bounds access
```
